### PR TITLE
Remove dead channels together with code

### PR DESCRIPTION
**Pull request by santomet**
Apart from CNN Portugal, nothing worked for me. Maybe some geoblocking somewhere?
Therefore, I removed all the code. Also, now all dead channels are redirected to our video_unavailable playlist.

Any comments? Does anyone have plans to maintain outside Czechoslovakia?

### CODE REVIEW

**Comment by NexusSfan** [comment]
Don't break playlists. Redirect non-working channels to unavailable.m3u8 using a 302 Found HTTP code.

**Comment by santomet** [comment]
Can you please provide a little more explanation as to why is this needed? The fact that some channel is dead, does not mean that it will be so forever 100%. Maybe I do not know enough about playlist bots, so please elaborate.

**Comment by NexusSfan** [comment]
> Can you please provide a little more explanation as to why is this needed? The fact that some channel is dead, does not mean that it will be so forever 100%.
Then use HTTP Code "302 Found"
> Maybe I do not know enough about playlist bots, so please elaborate.
If a playlist contains a dead m3u8 file without an error message (or even a 404) then its like connecting to a website and getting HTTP Code 200 every time, no matter what.

If you do not want this feature, that's okay.

**Comment by santomet** [comment]
Well, I still think it is unnecessary and potentially misleading. 301 has its meaning and it is actually different from our issue. Nothing moved permanently - it is just dead and we provide information for the user in the video, because video players do not care about status codes too much. 404 would have closer meaning but it is not compatible with redirecting (the header is overridden by 302 by default if you attempt to redirect)

However, OK. The only real use it could have hypothetically is that some bots might be able to filter out "permanently moved" links... If the bot knows what that means.

**Pull request merged**
